#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
# 文件: error.py
# 说明: 
# 时间: 2022/12/28 18:25:15
# 作者: Azure
# 版本: 1.0

class BotError(Exception):...

class NeedBuildError(BotError):...

# 配置文件相关
class ConfigError(BotError):...
class ConfigFileNotFoundError(ConfigError):...
class ConfigParserError(ConfigError):...
class ConfigFileSaveError(ConfigError):...

# Task Err
class TaskError(BotError):...

# 邮件相关
class EmailError(BotError):...
